# List of all the board related files.
BOARDCPPSRC =  $(PROJECT_DIR)/config/boards/core8/board_configuration.cpp

BOARDINC = $(PROJECT_DIR)/config/boards/core8

# Override DEFAULT_ENGINE_TYPE
DDEFS += -DSTM32F407xx
DDEFS += -DSHORT_BOARD_NAME=core8 -DDEFAULT_ENGINE_TYPE=MINIMAL_PINS
DDEFS += -DEFI_USE_OSC=TRUE
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=GPIOG_9
DDEFS += -DFIRMWARE_ID=\"core8\"
DDEFS += -DHAL_TRIGGER_USE_PAL=TRUE
DDEFS += -DHAL_VSS_USE_PAL=TRUE

# Hardware serial port on UART 2 -> PD5/PD6
DDEFS += -DSTM32_UART_USE_USART2=TRUE
DDEFS += -DTS_PRIMARY_UART=UARTD2
DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN=GPIOA_9 -DEFI_CONSOLE_RX_BRAIN_PIN=GPIOA_10

# Shared variables
ALLCPPSRC += $(BOARDCPPSRC)
ALLINC    += $(BOARDINC)
