pins:
  - id: GPIOF_13
    class: outputs
    ts_name: Low Side 1 (PF13)
    
  - id: GPIOF_14
    class: outputs
    ts_name: Low Side 2 (PF14)
    
  - id: GPIOD_8
    class: outputs
    ts_name: Low Side 3 (PD8)
    
  - id: GPIOD_9
    class: outputs
    ts_name: Low Side 4 (PD9)
    
  - id: GPIOD_10
    class: outputs
    ts_name: Low Side 5 (PD10)
    
  - id: GPIOD_11
    class: outputs
    ts_name: Low Side 6 (PD11)
    
  - id: GPIOD_12
    class: outputs
    ts_name: Low Side 7 (PD12)
    
  - id: GPIOD_13
    class: outputs
    ts_name: Low Side 8 (PD13)
    
  - id: GPIOD_14
    class: outputs
    ts_name: Low Side 9 (PD14)
    
  - id: GPIOD_15
    class: outputs
    ts_name: Low Side 10 (PD15)
    
  - id: GPIOG_2
    class: outputs
    ts_name: Low Side 11 (PG2)
    
  - id: GPIOG_3
    class: outputs
    ts_name: Low Side 12 (PG3)
    
  - id: GPIOG_4
    class: outputs
    ts_name: Low Side 13 (PG4)
    
  - id: GPIOG_5
    class: outputs
    ts_name: Low Side 14 (PG5)
    
  - id: GPIOG_6
    class: outputs
    ts_name: Low Side 15 (PG6)
    
  - id: GPIOG_7
    class: outputs
    ts_name: Low Side 16 (PG7)
    
  - id: GPIOG_8
    class: outputs
    ts_name: Low Side 17 (PG8)
    
  - id: GPIOC_6
    class: outputs
    ts_name: Low Side 18 (PC6)
    
  - id: GPIOC_7
    class: outputs
    ts_name: Low Side 19 (PC7)
    
  - id: GPIOA_8
    class: outputs
    ts_name: Low Side 20 (PA8)
    
  - id: GPIOD_5
    class: outputs
    ts_name: Low Side 21 (PD5)
    
  - id: GPIOD_4
    class: outputs
    ts_name: Low Side 22 (PD4)
    
  - id: GPIOD_3
    class: outputs
    ts_name: Low Side 23 (PD3)
    
  - id: GPIOA_15
    class: outputs
    ts_name: Low Side 24 (PA15)
        
  - id: GPIOE_15
    class: outputs
    ts_name: High Side 1 (PE15)
        
  - id: GPIOE_14
    class: outputs
    ts_name: High Side 2 (PE14)
        
  - id: GPIOE_13
    class: outputs
    ts_name: High Side 3 (PE13)
        
  - id: GPIOE_12
    class: outputs
    ts_name: High Side 4 (PE12)
        
  - id: GPIOE_11
    class: outputs
    ts_name: High Side 5 (PE11)
        
  - id: GPIOF_15
    class: outputs
    ts_name: High Side 6 (PF15)
        
  - id: GPIOG_0
    class: outputs
    ts_name: High Side 7 (PG0)
        
  - id: GPIOG_1
    class: outputs
    ts_name: High Side 8 (PG1)
        
  - id: GPIOE_7
    class: outputs
    ts_name: High Side 9 (PE7)
        
  - id: GPIOE_10
    class: outputs
    ts_name: High Side 10 (PE10)
        
  - id: GPIOE_9
    class: outputs
    ts_name: High Side 11 (PE9)
        
  - id: GPIOE_8
    class: outputs
    ts_name: High Side 12 (PE8)
        
  - id: GPIOF_7
    class: outputs
    ts_name: Stepper Direction (PF7)
        
  - id: GPIOF_8
    class: outputs
    ts_name: Stepper Control (PF8)
        
  - id: GPIOF_9
    class: outputs
    ts_name: Stepper Disable (PF9)
        
  - id: GPIOB_7
    class: outputs
    ts_name: DBW Disable (PB7)
        
  - id: GPIOB_8
    class: outputs
    ts_name: DBW Control (PB8)
        
  - id: GPIOB_9
    class: outputs
    ts_name: DBW Direction (PB9)
    
  - id: EFI_ADC_0
    class: analog_inputs
    ts_name: On-board Battery Sense (PA0)
    
  - id: EFI_ADC_1
    class: analog_inputs
    ts_name: Analog Inputs 1 (PA1)
    
  - id: EFI_ADC_2
    class: analog_inputs
    ts_name: Analog Inputs 2 (PA2)
    
  - id: EFI_ADC_3
    class: analog_inputs
    ts_name: Analog Inputs 3 (PA3)
    
  - id: EFI_ADC_4
    class: analog_inputs
    ts_name: Analog Inputs 4 (PA4)
    
  - id: EFI_ADC_5
    class: analog_inputs
    ts_name: On-board MAP (PA5)
    
  - id: EFI_ADC_6
    class: analog_inputs
    ts_name: Analog Inputs 6 (PA6)
    
  - id: EFI_ADC_7
    class: analog_inputs
    ts_name: Analog Inputs 7 (PA7)
    
  - id: EFI_ADC_8
    class: analog_inputs
    ts_name: On-board BARO (PB0) 
    
  - id: EFI_ADC_9
    class: analog_inputs
    ts_name: Analog Inputs 9 (PB1)
    
  - id: EFI_ADC_10
    class: analog_inputs
    ts_name: Primary On-board O2 (PC0)
    
  - id: EFI_ADC_11
    class: analog_inputs
    ts_name: Secondary On-board O2 (PC1)
    
  - id: EFI_ADC_12
    class: analog_inputs
    ts_name: Analog Inputs 12 (PC2)    
    
  - id: EFI_ADC_13
    class: analog_inputs
    ts_name: Analog Inputs 13 (PC3)
    
  - id: EFI_ADC_14
    class: analog_inputs
    ts_name: Analog Inputs 14 (PC4)
    
  - id: EFI_ADC_15
    class: analog_inputs
    ts_name: Analog Inputs 15 (PC5)    

  - id: GPIOE_2
    class: event_inputs
    ts_name: VR/Hall 1 (PE2)
    type: vr hall

  - id: GPIOE_3
    class: event_inputs
    ts_name: VR/Hall 2 (PE3)

  - id: GPIOE_4
    class: event_inputs
    ts_name: VR/Hall 3 (PE4)

  - id: GPIOE_5
    class: event_inputs
    ts_name: VR/Hall 4 (PE5)

  - id: [GPIOF_5, GPIOF_5]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 1 (PF5)

  - id: [GPIOF_4, GPIOF_4]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 2 (PF4)

  - id: [GPIOF_3, GPIOF_3]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 3 (PF3)

  - id: [GPIOF_2, GPIOF_2]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 4 (PF2)

  - id: [GPIOF_1, GPIOF_1]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 5 (PF1)

  - id: [GPIOF_0, GPIOF_0]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 6 (PF0)

  - id: [GPIOE_6, GPIOE_6]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 7 (PE6)

  - id: [GPIOC_13, GPIOC_13]
    class: [switch_inputs, event_inputs]
    ts_name: Digital Input 8 (PC13)

info:
  title: Core8
  name: Core8
  board_url: https://rusefi.com/s/core8